[window]

opacity = 0.9

blur = true

padding.x = 10
padding.y = 10

decorations = "Full"
decorations_theme_variant = "Dark"

dimensions = { columns = 100, lines = 30 }

[terminal]

shell = { program = "nu" }

[font]
normal.family = "Hack Nerd Font"